[build]
  command = "npm install"
  publish = "."

[[redirects]]
  from = "/:code"
  to = "/.netlify/functions/redirect/:code"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
